{
 "title": "HW-4",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency 50%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le,pod) (rate(http_server_requests_seconds_bucket{uri=~\"/users\"}[1m])))*1000",
     "legendFormat": "{{pod}}, ms"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"hw4-hw4-chart\"}[1m])) by (le))*1000",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "Latency 95%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le,pod) (rate(http_server_requests_seconds_bucket{uri=~\"/users\"}[1m])))*1000",
     "legendFormat": "{{pod}}, ms"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"hw4-hw4-chart\"}[1m])) by (le))*1000",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "Latency 99%",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le,pod)(rate(http_server_requests_seconds_bucket{uri=~\"/users\"}[1m])))*1000\t",
     "legendFormat": "{{pod}}, ms"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"hw4-hw4-chart\"}[1m])) by (le))*1000",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(http_server_requests_seconds_bucket{uri=~\"/users\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count{ingress=\"hw4-hw4-chart\"}[1m]))",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "ErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "sum by (pod) (increase(http_server_requests_seconds_bucket{uri=~\"/users\", status=~\"5.+\"}[1m]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))",
     "legendFormat": "nginx-ingress"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{pod=~\"hw4-hw4.*\"}/(1024*1024)",
     "legendFormat": "{{pod}}, mb"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"hw4-hw4.*\"}[3m])",
     "legendFormat": "{{pod}}, mb"
    }
   ]
  },
  {
   "title": "DB Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(rate(container_memory_usage_bytes{pod=\"hw4-postgresql-0\"}[5m]))/1000",
     "legendFormat": "resident mem, kB"
    }
   ]
  },
  {
   "title": "DB CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=\"hw4-postgresql-0\"}[1m]))",
     "legendFormat": "db"
    }
   ]
  },
  {
   "title": "Fetch (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"user_db\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}