apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  postgres_user: {{ .Values.postgresql.auth.username | b64enc }}
  postgres_password: {{ .Values.postgresql.auth.password | b64enc }}
  postgres_database: {{ .Values.postgresql.auth.database | b64enc }}

  JWT_SECRET: {{ .Values.auth_salt | b64enc }}