# my-kafka-chart/values.yaml
kafka:
  imageName: "docker.io/bitnami/kafka:3.7"
  replicas: 1
  nodeID: "0"
  processRoles: "controller,broker"
  controllerQuorumVoters: "0@kafka:9093"
  listeners: "PLAINTEXT://:9092,CONTROLLER://:9093"
  advertisedListeners: "PLAINTEXT://:9092"
  listenerSecurityProtocolMap: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
  controllerListenerNames: "CONTROLLER"
  interBrokerListenerName: "PLAINTEXT"

service:
  name: "kafka"
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
  clusterIP: None
