apiVersion: v1
kind: Service
metadata:
  name: hw2
spec:
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  selector:
    app: hw2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2
  labels:
    app: hw2
spec:
  selector:
    matchLabels:
      app: hw2
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: hw2
    spec:
      containers:
      - name: hw2
        image: tvv766/hw1
        ports:
        - containerPort: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hw2-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/health(/?)$ /health break;
      rewrite ^/otusapp/(.+)/(.*) /$2 break;
spec:
  ingressClassName: nginx
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hw2
            port:
              number: 8000