replicaCount: 1

application:
  deployment:
    pod:
      repository: tvv766/hw6-billing-app
      pullPolicy: Never
      tag: "latest"
      #tag: v1
      port: 80
  service:
    type: LoadBalancer
    port: 8081

postgresql:
  enabled: true
  auth:
    username: usr
    password: pwd
    database: user_db
  service:
    port: "5432"

auth_salt: "123"